language: objective-c
osx_image: xcode9.4

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

install:
- bundle install

script:
- set -e
- fastlane beta
- git clone https://github.com/apptestai/ci_addon
- chmod +x ./ci_addon/travis_phase.sh
- export binary_path=HackerNews.ipa
- export project_id='825'
- "./ci_addon/travis_phase.sh"

deploy:
  provider: releases
  api_key:
    secure: HaKogFn1RbvuSmbJg9d6GeksFV50XHHxs9+ykaC17a+kKSGs/B6SbmXrJweBXPknsbalxTPNcqKYeh81MzHv/nh06k/86yQSp7l1ZlKJYusEfeWsQIddnmHexBg0y0gqREL2bhWXNB1fgzM3UHiBGSi8Q8DF+p1mg0sfo/0r8wh7Ls2ishQG7ibG0ePoricN/NodNj+EVgFIwB3jn9A8Kyb8Uz8bUI6Pd6cpQOMCrzMfuOeOBA5x6Ca0yv21FEJ+NrwNChzvpR2YRXDYuVlhJi2lxJqGQ4oz11g7QBqPbivEWR0pcmEfy6gR3h/d7IrEBJ/Z0QL3cG+9xOyrqH6II831BhXyhoK63e7Kr2wXMR0209mPoyLpLYVY7E/mNnfgUU1PgEzQV9NifCxoPHh8Wa0CuV4cm7NxetPQrUjJpxp7zx3b70zynuv6lF8t+f0fz12E+ZarXmHa7bWN5pE5c1gug/JQyzDSqL5hyv+mngHoWQDqjyqHtNI0zvPIgF+iOc6PGSt3Exp5MugUn/GWXAHk5QOJ9P4UOZFEbMMhVj8ODGP2uiJ4j5KDT4zjrgMQ7JClVixRZh8imj/SQxJX8Fc+X/jqCcj0u2Zkn53k2t26rVkBc3ZNxqm5oIWSpgtj/wOHRrQrY5CE4gkcCNwjNAT56B2WV4KA9WVSByi33EU=
  file:
  - ./test-results/apptest-ai_result.html
  skip_cleanup: true


env:
  global:
  - secure: fUnmuuqKmxWjxGHbfTB7QZgSmkB7yvt6KGAn8dCs1j4GneWbSIrEhghRrlOMQCThhMoetou4H+NaWeTXRRa4fpoCGm1U51RbD+J4DrbKWj3MzRupzByEAsaWhmvCaYVgCOlkYgaApcvujIrpw1rUTQVio8+WoYIXgXx3BZF06VN50oNT58BUZAD/UUeEacp8GEI5tcPbsbaKbPqy2Rb5HSQ+RkSfAWJhuA+x4RT8l8geXRdUhtrT00EasL7a7p/4OIPkW4pAGvBth/jiDoWA3N2tDME7AOU+whvt9tVju9Db/WKarWYCkPuSVwHTUH6W9o3TyvLLgAsapbgrS7DtJkJx5NoPNyZa5WrlnOdNAerSgQRC724sfSM4dHrYhkSWHRueAjD9X0JbS5TEUeTnw2XHbq+hbc/5aFR/CnZFkTSv6XItnL6ES6tz/nQjNZfIdsHRFfoTCre1Uah3zAu0veHh7d1srvq91lvc3VSrnuhSoNpegPSc1NZ5dmN1VkhLRt7q8hSU1HMpBYe76q58UyfS02BjTswQJOoQHmBDl+DDv045qi4q1/hfCd/JqGNgH3bp2KtZxV0uq+aUicC7XWhaHyaVaGnVJa94kqayxNsoFP3zOse//VlIL46iHDSpuIzXCcgR2IT59T+E5i/c1fOzA65KEn8Aw7cr/5R8W2s=
  - secure: yXlFmmgo3QIeH43qSeKTol7Fl/IWvKGLh3ycAdgTnFUfocPnHYhIV3b0ykvoLxSyDPeV/Rre8uhAXLAas3w/XFYWOvobE/qgEDbc+7dYKT5xWXqaW9MfYVnnVsuBgDZNPdHsZPyclF+q4H5Y2Le8b9VCkXIHxmspHrFXnTt7mRqCf9xPFBJCQKFfMTQs2sOBuILh2SpOP39seNyX52p4cPg2ZRpncghml86JScuwRSFrBlI2vDBvQLzT0SenDtsmnVQfGdVTw6Vp8IfapvNp9FXakPdSuwovNQAANhSAMyCwaTb08gXS04OSIPl+DwezZnDzhdpisL5RPYQEbjSGk70l536AaM1VOoAN4991fyW5aLf93vDqEnh5TmBQqrK/RD3KsUaCcXh/cwk3yRvB3Wt1LdTX+NV1FnE4kwDodF+zB6ueumFinG1Qkx4HV8RanDvRGKSxK89SlDXCbiZ/tl8vzIdPh5p4u4/+Lxt8iPgIA/0MovpQFDVnmEGpRoPclwSHBu2tt6LLH57+n7r3Wd1C0aMMzM+Nr582MrxGkxPGBIA84741Vy5g3hZ9aTF9VSz5+sHseelXZYQcGXDNNZbeFy3rtNgavQVETsXDu1c2kWNvkPxoPl9SNmxMn1mNIb5ROCCQjku5icAyZFE+3zwGLFnSWn0WaN5mqZs+Dqc=
  - secure: CzEyJF6epoEK9E8FmSO4QuxiKssdn0te84Mvaqrp2F4atueiZYntAryxEobEx8bZFu3tdCGlDPbgyoo7W4goRc/zij4P41C/LtAxqQWvz4KGCpADJsGYGYij+0DHbwZpgbN9sg1o32NjDRNx+uAxzp/iGyIkwC8wA4CVSXzKsfyQ2LMHDtZbKeDj+ZxOjRfzVD9461KgFpIYWZTmmHVS6n0/EfOP7WEVaZmehlOV8kpsO59E/YMD0U6STvmwa+4+9tyYT3mKJEH1GcxePbWz5oyxCmcvhrKhBmhIvbndA7lFcXW/4/sr6Mrf38/8wChQqRweiZyFk5M1lMAnKfOgwP2H9K8LbxKE+hv5MpC2FPq1h1z8BM8/OfFEZjgYClA5/YN7MMpyP2G25z9n8bYu8d3hkOASi23lQVMjIPwyCe9OCrQofpn7dI3WvvmT/+vYGxBqWFrLlHYRMRlYzFaesUwc00BBdxmirCk+BSwS5Lq0iOvEdyHM6A+QokHMHKAJxKZFZ9LvOF3G5sDB2b3oiuKszf7qqm3JRT4271tB2JWvyIc+jey/DU2VOaP79RFAizsw2sIsHiOULl1HHCrHamLLknnKpGYVesrfAjecAoW9eSubrq+qtSZXUUf+AtTquVqmgSl11G+ZFfCWrxVu5X9yb0VA0mUY/rFU/xoS/Co=
