version: 2.1
orbs:
  apptest-ai: apptestai/ios-app-test@dev:0.0.2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Build and archive
          command: fastlane ios beta
      - apptest-ai/run-test:
          binary_path: ./HackerNews.ipa
          project_id: '794'
      - store_artifacts:
          path: ./HackerNews.ipa
      - store_artifacts:
          path: ./apptest-ai_result.html
      - store_test_results:
          path: .
      
