version: 2.1

orbs:
  apptest-ai: apptest-ai/run-test@volatile

jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: Build and archive
          command: fastlane ios beta
      - apptest-ai/run-test:
         binary_path: app/build/outputs/apk/debug/app-debug.apk
         access_key: d0b20cd289994be0e423e2c42f4c09fe
         project_id: '793'
      - store_artifacts:
          path: ./HackerNews.ipa
          destination: application binary
      - store_artifacts:
          path: $(TMP_DIR)/apptest_results.json
          destination: app test results
