version: 2
jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: Build and archive
          command: fastlane ios beta
      - store_artifacts:
          path: ./HackerNews.ipa
          destination: application binary
